# Eureka common configurations
eureka:
  client:
    fetch-registry: true  # by default true
    register-with-eureka: true  # by default true
    service-url:
      defaultZone: http://localhost:8761/eureka  # where our eureka server is running
  instance:
    prefer-ip-address: true  # when guessing the hostname the IP address of the server should be used in preference to the hostname

# OpenAPI common configurations
springdoc:
  api-docs:
    path: /api-docs   # default path is /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html  # default path is /swagger-ui/index.html
    operationsSorter: method  # sort API paths based on HTTP methods
